(() => {
'use strict';const V=window.SohbetixV29,$=id=>document.getElementById(id);
const target=V.cleanNick(new URLSearchParams(location.search).get('nick')||sessionStorage.getItem('sohbetix-v17-current-nick')||'');
const profile=V.getProfileByNick(target);if(!profile||String(profile.ownerId)!==String(V.currentUserId())){location.replace('profile.html?nick='+encodeURIComponent(target));return;}
let data=V.getProfileDataByProfile(profile);const user=V.profileOwnerUser(profile),vip=V.isVipUser(user);
$('profileBackV29').href='profile.html?nick='+encodeURIComponent(target);
const countries=['','Afganistan','Almanya','Amerika Birleşik Devletleri','Andorra','Angola','Antigua ve Barbuda','Arjantin','Arnavutluk','Avustralya','Avusturya','Azerbaycan','Bahamalar','Bahreyn','Bangladeş','Barbados','Belarus','Belçika','Belize','Benin','Bhutan','Birleşik Arap Emirlikleri','Birleşik Krallık','Bolivya','Bosna-Hersek','Botsvana','Brezilya','Brunei','Bulgaristan','Burkina Faso','Burundi','Cabo Verde','Cezayir','Cibuti','Çad','Çekya','Çin','Danimarka','Dominika','Dominik Cumhuriyeti','Doğu Timor','Ekvador','Ekvator Ginesi','El Salvador','Endonezya','Eritre','Ermenistan','Estonya','Esvatini','Etiyopya','Fas','Fiji','Fildişi Sahili','Filipinler','Filistin','Finlandiya','Fransa','Gabon','Gambiya','Gana','Grenada','Guatemala','Gine','Gine-Bissau','Guyana','Güney Afrika','Güney Kore','Güney Sudan','Gürcistan','Haiti','Hindistan','Hollanda','Honduras','Hırvatistan','Irak','İran','İrlanda','İspanya','İsrail','İsveç','İsviçre','İtalya','İzlanda','Jamaika','Japonya','Kamboçya','Kamerun','Kanada','Karadağ','Katar','Kazakistan','Kenya','Kırgızistan','Kiribati','Kolombiya','Komorlar','Kongo Cumhuriyeti','Kongo Demokratik Cumhuriyeti','Kosta Rika','Kuveyt','Kuzey Kore','Kuzey Makedonya','Küba','Kıbrıs','Laos','Lesotho','Letonya','Liberya','Libya','Lihtenştayn','Litvanya','Lübnan','Lüksemburg','Macaristan','Madagaskar','Malavi','Maldivler','Malezya','Mali','Malta','Marshall Adaları','Mauritius','Meksika','Mısır','Mikronezya','Moğolistan','Moldova','Monako','Moritanya','Mozambik','Myanmar','Namibya','Nauru','Nepal','Nijer','Nijerya','Nikaragua','Norveç','Orta Afrika Cumhuriyeti','Özbekistan','Pakistan','Palau','Panama','Papua Yeni Gine','Paraguay','Peru','Polonya','Portekiz','Romanya','Ruanda','Rusya','Saint Kitts ve Nevis','Saint Lucia','Saint Vincent ve Grenadinler','Samoa','San Marino','Sao Tome ve Principe','Senegal','Seyşeller','Sierra Leone','Singapur','Sırbistan','Slovakya','Slovenya','Solomon Adaları','Somali','Sri Lanka','Sudan','Surinam','Suriye','Suudi Arabistan','Şili','Tacikistan','Tanzanya','Tayland','Togo','Tonga','Trinidad ve Tobago','Tunus','Tuvalu','Türkiye','Türkmenistan','Uganda','Ukrayna','Umman','Uruguay','Ürdün','Vanuatu','Vatikan','Venezuela','Vietnam','Yemen','Yeni Zelanda','Yunanistan','Zambiya','Zimbabve'];
$('countryV29').innerHTML=countries.map(c=>`<option>${c}</option>`).join('');
$('birthDayV29').innerHTML='<option value="">Gün</option>'+Array.from({length:31},(_,i)=>`<option>${i+1}</option>`).join('');
$('birthMonthV29').innerHTML='<option value="">Ay</option>'+Array.from({length:12},(_,i)=>`<option>${i+1}</option>`).join('');
const cy=new Date().getFullYear();$('birthYearV29').innerHTML='<option value="">Yıl</option>'+Array.from({length:100},(_,i)=>`<option>${cy-13-i}</option>`).join('');
function syncHex(color,hex){hex.value=color.value.toUpperCase();}function syncColor(hex,color){if(/^#[0-9a-f]{6}$/i.test(hex.value))color.value=hex.value;}
$('editNickV29').value=profile.nick;$('editGenderV29').value=data.gender;$('birthDayV29').value=data.birthDay;$('birthMonthV29').value=data.birthMonth;$('birthYearV29').value=data.birthYear;$('countryV29').value=data.country;$('maritalV29').value=data.marital;$('aboutV29').value=data.about;$('nickColorV29').value=data.nickColor;$('nickHexV29').value=data.nickColor;$('textColorV29').value=data.textColor;$('textHexV29').value=data.textColor;$('boldNickV29').checked=!!data.boldNick;$('boldTextV29').checked=!!data.boldText;$('privateEnabledV29').checked=data.privateEnabled!==false;$('aboutCountV29').textContent=$('aboutV29').value.length;
$('aboutV29').oninput=()=>$('aboutCountV29').textContent=$('aboutV29').value.length;$('nickColorV29').oninput=()=>syncHex($('nickColorV29'),$('nickHexV29'));$('nickHexV29').oninput=()=>syncColor($('nickHexV29'),$('nickColorV29'));$('textColorV29').oninput=()=>syncHex($('textColorV29'),$('textHexV29'));$('textHexV29').oninput=()=>syncColor($('textHexV29'),$('textColorV29'));
if(!vip){$('boldNickV29').disabled=true;$('boldTextV29').disabled=true;}
function cooldown(){const until=Number(data.lastNickChangedAt||0)+V.MONTH_30,left=until-Date.now();if(Number(data.lastNickChangedAt||0)&&left>0){$('editNickV29').disabled=true;const days=Math.floor(left/86400000),hours=Math.floor((left%86400000)/3600000),mins=Math.floor((left%3600000)/60000),secs=Math.floor((left%60000)/1000);$('nickCooldownV29').textContent=`Nick değişimine ${days} gün ${hours} sa ${mins} dk ${secs} sn kaldı.`;}else{$('editNickV29').disabled=false;$('nickCooldownV29').textContent='Nick 30 günde 1 kez değiştirilebilir.';}}cooldown();setInterval(cooldown,1000);
$('profileEditFormV29').onsubmit=e=>{e.preventDefault();const st=$('profileEditStatusV29'),newNick=V.cleanNick($('editNickV29').value);if(!newNick){st.textContent='Nick boş olamaz.';return;}let p=profile;if(newNick!==profile.nick){if($('editNickV29').disabled){st.textContent='Nick değiştirme süresi henüz dolmadı.';return;}if(!V.nickAvailable(newNick,profile.id)){st.textContent='Bu nick kullanılamıyor.';return;}const list=V.readProfiles(profile.ownerId),idx=list.findIndex(x=>x.id===profile.id);if(idx>=0){list[idx]={...list[idx],nick:newNick,updatedAt:Date.now()};V.writeProfiles(profile.ownerId,list);}V.removeNickFromAllPresence(profile.nick);sessionStorage.setItem('sohbetix-v17-current-nick',newNick);data.lastNickChangedAt=Date.now();profile.nick=newNick;}
const next={...data,gender:$('editGenderV29').value,birthDay:$('birthDayV29').value,birthMonth:$('birthMonthV29').value,birthYear:$('birthYearV29').value,country:$('countryV29').value,marital:$('maritalV29').value,about:$('aboutV29').value.slice(0,5000),nickColor:$('nickHexV29').value,textColor:$('textHexV29').value,boldNick:vip&&$('boldNickV29').checked,boldText:vip&&$('boldTextV29').checked,privateEnabled:$('privateEnabledV29').checked};V.saveProfileData(profile.id,next);data=next;st.textContent='✓ Değişiklikler kaydedildi.';setTimeout(()=>location.href='profile.html?nick='+encodeURIComponent(profile.nick),500);};
$('deleteProfileV29').onclick=()=>{if(!confirm('Bu profili tamamen silmek istediğinizden emin misiniz? Bu nick tekrar kullanılamaz.'))return;V.reserveDeletedNick(profile.nick);const list=V.readProfiles(profile.ownerId).filter(x=>x.id!==profile.id);V.writeProfiles(profile.ownerId,list);localStorage.removeItem(V.profileDataKey(profile.id));V.removeNickFromAllPresence(profile.nick);if(V.norm(sessionStorage.getItem('sohbetix-v17-current-nick'))===V.norm(profile.nick))sessionStorage.removeItem('sohbetix-v17-current-nick');location.replace('open-chat.html');};
})();
